# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 'curlimages/curl'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: cURL whatsmyip
        run: |
          curl -sSL -4 icanhazip.com

  # https://github.com/actions/runner
  my-self_hosted-run:

    needs: build

    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: echo "::set-env name=DAY_OF_WEEK::$( date +%a )"

      - name: printenv
        run: |
          printenv

      - name: Stars and forks
        run: |
          STARS=$(jq --raw-output .repository.stargazers "${{ github.event_path }}")
          FORKS=$(jq --raw-output .repository.forks "${{ github.event_path }}")
          echo "${{ github.repository }} has $STARS stars and $FORKS forks"
        if: github.event_name == 'workflow_dispatch'

      - name: Dig whatsmyip
        run: |
          dig +short myip.opendns.com @resolver1.opendns.com
        if: env.DAY_OF_WEEK == 'Mon'
